handlers = java.util.logging.ConsoleHandler
.level = FINER


fileHandler.pattern = %h/AppData/Roaming/Hello Messenger/logs/log%g-%u.txt
fileHandler.limit = 10485760
fileHandler.count = 5
fileHandler.level = FINER
fileHandler.maxLocks = 100
fileHandler.formatter = com.github.rob269.helloMessengerClient.LogFormatter

java.util.logging.ConsoleHandler.level = FINER
java.util.logging.ConsoleHandler.formatter = com.github.rob269.helloMessengerClient.LogFormatter


javafx.level = OFF
com.sun.javafx.level = OFF